<?php
/**
 * Asset loader.
 *
 * @package AcmePlugin
 */

declare(strict_types=1);

namespace AcmePlugin\Assets;

/**
 * Enqueues compiled assets for each WordPress context.
 *
 * Each entry point produces a *.asset.php file via DependencyExtractionWebpackPlugin
 * that lists the correct WordPress script handles as dependencies. This ensures
 *
 * @wordpress/* packages are loaded from WP core rather than bundled.
 */
final class AssetLoader {

	/**
	 * Base URL of the plugin directory.
	 *
	 * @var string
	 */
	private string $plugin_url;

	/**
	 * Asset version string for cache-busting.
	 *
	 * @var string
	 */
	private string $version;

	/**
	 * Constructor.
	 *
	 * @param string $plugin_url Base URL of the plugin directory.
	 * @param string $version    Asset version string.
	 */
	public function __construct(
		string $plugin_url,
		string $version,
	) {
		$this->plugin_url = $plugin_url;
		$this->version    = $version;
	}

	/** Enqueue frontend scripts and styles. */
	public function enqueue_frontend(): void {
		$this->enqueue_bundle( 'frontend' );
	}

	/** Enqueue block editor scripts and styles. */
	public function enqueue_editor(): void {
		$this->enqueue_bundle( 'editor' );
	}

	/** Enqueue wp-admin scripts and styles. */
	public function enqueue_admin(): void {
		$this->enqueue_bundle( 'admin' );
	}

	/**
	 * Enqueue a named asset bundle.
	 *
	 * @param string $name Bundle name (matches the webpack entry point key).
	 */
	private function enqueue_bundle( string $name ): void {
		$asset = $this->load_asset_file( $name );

		if ( null === $asset ) {
			return;
		}

		wp_enqueue_script(
			"acme-plugin-{$name}",
			$this->plugin_url . "build/{$name}.js",
			$asset['dependencies'],
			$asset['version'],
			[ 'in_footer' => true ],
		);

		if ( file_exists( ACME_PLUGIN_DIR . "build/{$name}.css" ) ) {
			wp_enqueue_style(
				"acme-{$name}",
				$this->plugin_url . "build/{$name}.css",
				[],
				$asset['version'],
			);
		}
	}

	/**
	 * Load the asset manifest generated by DependencyExtractionWebpackPlugin.
	 *
	 * @param string $name Bundle name.
	 * @return array{dependencies: string[], version: string}|null Null when the file does not exist.
	 */
	private function load_asset_file( string $name ): ?array {
		$file = ACME_PLUGIN_DIR . "build/{$name}.asset.php";

		if ( ! file_exists( $file ) ) {
			return null;
		}

		return require $file;
	}
}
